import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";
import FooterPage from "@/components/shared/Footer";
import { cn } from "@/utils/utils";


const font = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Manik | Hossain",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" data-theme="light">
      <body
        className={cn(
          font.className,
          "flex min-h-screen flex-col bg-[#F5F2F2]"
        )}
      >
        <Navbar session={session} />
        <div className=" w-[75%] mx-auto">
          {children}
        </div>
        <FooterPage />
      </body>
    </html>
  );
}
