import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "@/utils/authOptions";
import FooterPage from "@/components/shared/Footer";
import { AnimatePresence } from "framer-motion";

export const metadata: Metadata = {
  title: "Manik | Home",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" data-theme="light">
      <body className="bg-[#F5F2F2]">
        <Navbar session={session} />
        <div className="w-[75%]  mx-auto">{children}</div>
        <FooterPage />
      </body>
    </html>
  );
}
