import Sidebar from "@/components/shared/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Manik | Career",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className=" my-2 ">
      <div className="flex flex-col md:flex-row justify-between space-y-3">
        <div className="w-[100%] md:w-[20%]">
          <Sidebar />
        </div>
        <div className="w-[100%] md:w-[80%] rounded-box p-5">{children}</div>
      </div>
    </div>
  );
}
