import Sidebar from "@/components/shared/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Manik | Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="my-2">
  <div className="flex flex-col md:flex-row justify-between">
    {/* Sidebar */}
    <div className="w-full md:w-[20%] bg-slate-300">
      <Sidebar />
    </div>

    {/* Main content */}
    <div className="w-full md:w-[80%] bg-slate-200 rounded-box ml-0 md:ml-2 mt-2 md:mt-0">
      {children}
    </div>
  </div>
</div>
  );
}
